### PR TITLE
Make target repository for deployment configurable

### PR DESCRIPTION
**Pull request by cedricziel**
# Proposed Changes

In order to make the workflow for deployment more reusable, this introduces 3 new parameters to configure the target repositories.

They use defaults that match the current org layout

### CODE REVIEW

**Comment by frenck** [comment]
Why? I don't see the use for it in this project?
Are there follow-up PRs you are planning to make in other parts of this project?

**Comment by cedricziel** [comment]
I would like to reuse it with my own repository. The workflows are otherwise pretty flexible and this is a missing piece for me

**Comment by frenck** [comment]
Have you read the readme of this repo?

**Comment by cedricziel** [comment]
Yes. Did I miss something?

**Comment by frenck** [comment]
These workflows are for the community add-ons. You are free to use them, but we don't recommend using them. They are subjected to change and not bound by versioning.

These workflows are here to power these add-ons. Unless this change has an advantage for this project, I'm not really in favor of adding an unneeded configuration.

Hence my initial question here:

<https://github.com/hassio-addons/workflows/pull/74#issuecomment-1345572211>

What is the use for the change for this project?

../Frenck

**Comment by cedricziel** [comment]
There is no use for the `hassio-addons` project since you have fixed names for the repos.

I proposed the change because I thought it's easy enough and provides value to my projects. It's absolutely your choice if you want to accept it or not.

**Comment by frenck** [comment]
The things is, I'm not planning on supporting this as a generic workflow for others to use.
Accepting additions that make that possible, and aren't use by this project IMHO provides the wrong signal.

**Review by frenck — APPROVED** [review]
Alright, this one has been pending for a bit... Which made me think: Why not?

Use at your own risk though :)

../Frenck

**Pull request merged**
